[package]
name = "chat-example"
version = "0.1.0"
edition = "2021"

[dependencies]
flurry = { path = "../../" }
nix = "0.29.0"
rand = "0.8.5"


[[bin]]
name = "benchmark"
path = "benchmark.rs"


[[bin]]
name = "replay"
path = "replay.rs"


[[bin]]
name = "fork"
path = "fork.rs"
